[package]
name = "avltree"
version = "0.1.0"
authors = ["myself659 <myself659@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

quickcheck = "0.8.5"
quickcheck_macros = "0.8.0"
itertools = "0.8.0"